# Generated by Django 2.2.2 on 2019-06-27 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='total_likes',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
